version: '3'

services:
  app:
    build: .
    ports:
      - "3000:80"
    volumes:
      - .:/app
      - /app/node_modules
      - ./data.json:/usr/share/nginx/html/data.json
    environment:
      - NODE_ENV=production
